# @package _global_
backbone:
  num_layers: null
  num_heads: null
  hidden_dim: null
  ffn_dim: null
  dropout: 0.1
  max_position_embeddings: null
  from_pretrained: false
  shift_audio_offset: 0
  force_weight_tying: false
