# @package _global_
training:
  seed: 42
  dataset_name: librispeech_aligned
  output_dir: outputs/hybrid_tts
  learning_rate: 1e-4
  min_learning_rate: 1e-6
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.0
  warmup_steps: 0
  uncond_prob: 0.0
  no_augment_ratio: 0.0
  discrete_only: false
  continuous_only: false
  online_encode: false
  audio_quantizer_source: z
  include_quantizer_residual: false
  semantic_quantizer_checkpoint: null
  semantic_quantizer_type: std_vq
  semantic_codebook_size: null
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1
  num_train_epochs: 100
  max_steps: -1
  logging_steps: 100
  eval_steps: 1000
  eval_num_samples: 100
  save_steps: 1000
  save_total_limit: 3
  report_to: wandb
  wandb_project: hybrid_tts
  wandb_run_name: baseline
  run_id: ""
  resume_from_checkpoint: null
