# @package _global_
training:
  dataset_name: librispeech-aligned #TODO this is handled with hardcoding, refactor in future
  output_dir: checkpoints/exps/debug-token_and_features-shift

  per_device_train_batch_size: 2
  gradient_accumulation_steps: 2
  logging_steps: 1
  # report
  report_to: none
  wandb_project: hybrid_tts
  wandb_run_name: debug-lj_speech_512-token_and_features-shift
  run_id: ""
  bf16: true
  # eval
  eval_strategy: "no"
  eval_steps: null
  save_steps: 10
  eval_num_samples: 4
  num_train_epochs: 100
  # lr
  learning_rate: 7e-5
  min_learning_rate: 1e-5
  lr_scheduler_type: "cosine"   
  warmup_ratio: 0.05         
  # cfg
  uncond_prob: 0.5
  no_augment_ratio: 0.8
  discrete_only: false
  group_by_length: false
  # use_cpu: false

backbone:
  model_type: "qwen-0.5b"
  from_pretrained: false
  shift_audio_offset: 1
  # force_weight_tying: false
  # num_layers: 4
  # num_heads: 8
  # hidden_dim: 512
  # ffn_dim: 2048
  # dropout: 0.1
  # max_position_embeddings: 8192

diffusion_head:
  net_dim: 512
  net_depth: 6
  uncond_prob: 0.0
  use_mlp_sampler: true

continuous_adapter:
  hidden_dim: 256
  num_layers: 2   # Crea 2 strati nascosti + strato di output

vae_checkpoint: "$SCRATCH/MelCausalVAE/checkpoints/exps/set10_512"
vocoder_checkpoint: "vocos"
debug: false
